import { Inter } from "next/font/google";
import React from 'react';
import { MediaContextProvider } from '../utils/media';
import Header from './Header';
import Footer from './Footer';
import "./globals.css";
import 'semantic-ui-css/semantic.min.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vintage Vista Vineyards",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MediaContextProvider>
    <Header />
    {children}
    <Footer />
  </MediaContextProvider>
  );
}
